export const userProjectionFields = {
  _id: 1,
  firstName: 1,
  middleName: 1,
  lastName: 1,
  emailId: 1,
  contact: 1,
  countryCode: 1,
  address: 1,
  profileImage: 1,
  isVerified: 1,
  isApproved: 1,
  isActive: 1,
  createdBy: 1,
  updatedBy: 1,
  createdAt: 1,
  updatedAt: 1,
  tokens: 1,
  role: 1,
  metadata: 1,
  resetPassword: 1,
  password: 1,
  sessionmetadata: 1,
};

export const blogProjectionFields = {
  _id: 1,
  title: 1,
  featuredImage: 1,
  customImage: 1,
  excerpt: 1,
  description: 1,
  category: 1,
  blogStatus: 1,
  publishDate: 1,
  slug: 1,
  createdBy: 1,
  modifiedBy: 1,
  isDeleted: 1,
  createdAt: 1,
  updatedAt: 1,
};
